### ISSUE TITLE
Identify RNA viruse with palmscan in the shotgun metagenome dataset?

### ISSUE THREAD

**Issue by biofuture** [rcedgar/palmscan#1]
Dear R.C. Edgar

I used the tool to search metagnomics contigs from a shotgun metagenome,  and find over 100 contigs having the RdRp with high scores.  It seems to indicate that there are RNA viruses in the whole genome shotgun metagenome data, which are assumed to be only DNA sequenced. 

Do you know what are the underlying reasons for this finding? 

Thank you very much.

**Comment by rcedgar** [comment]
No.

**Comment by biofuture** [comment]
Do you think why there are some contigs in the shotgun metagenome has RddRP detected?

Thank you.

**Comment by rcedgar** [comment]
Could be false positives by palmscan, mis-annotated data (e.g. SRA sometimes says DNA when in fact RNA), novel RTs... this is a complex biological question out of scope for issues of the open-source code for palmscan.

**Comment by biofuture** [comment]
Thanks, 

I used my own DNA metagenome data, so it has no possibility to have RNA in it if the extraction KIT did not have problem. 

I am thinking whether it is possible to be ds RNA  viruses that integrated into their host genome with RdRps in it.

The interesting part is that I find it present in both DNA metagenome and RNA metagenome from the same sample.  It is really confuse me. 

Thank you very  much.

**Comment by ababaian** [comment]
See: Endogenous Viral Elements (EVE), and/or this is contamination of your samples if you have a metatranscriptome with identical sequences.

**Comment by biofuture** [comment]
Thanks I thought as well. 

I find an interesting paper 

https://academic.oup.com/mbe/article/38/11/5082/6342421
RdRp or RT, That is the Question
